/**
 * Bundler-side loaders for the clean pool (Phase 3 loader swap). Static
 * imports of exactly the four N5 clean files keep N4-N1 and JLPT out of the
 * bundle entirely (docs/quality.md Phase-1 bundle scope). data/clean/ is the
 * app's single source of truth: generated by scripts/build-clean.mjs from the
 * frozen raw scrape plus owner adjudications; scripts/audit-clean.mjs proves
 * it defect-free. The e2e journey runs gate.ts's validators over fs-read
 * clean files instead, because bundler JSON imports do not load under bare
 * Node.
 */

import kanaRaw from "../../data/clean/kana.json";
import kanjiN5Raw from "../../data/clean/kanji_n5.json";
import vocabularyN5Raw from "../../data/clean/vocabulary_n5.json";
import grammarN5Raw from "../../data/clean/grammar_n5.json";
import { validateGrammar, validateKana, validateKanji, validateVocab } from "./gate";
import type { JlptLevel } from "./ids";
import type { GateResult, GrammarLesson, KanaItem, KanjiItem, VocabItem } from "./models";

export const CLEAN_SLICE_LEVEL: JlptLevel = "n5";

export function loadKana(): GateResult<KanaItem> {
  return validateKana(kanaRaw);
}

export function loadKanji(): GateResult<KanjiItem> {
  return validateKanji(kanjiN5Raw, CLEAN_SLICE_LEVEL);
}

export function loadVocab(): GateResult<VocabItem> {
  return validateVocab(vocabularyN5Raw, CLEAN_SLICE_LEVEL);
}

export function loadGrammar(): GateResult<GrammarLesson> {
  return validateGrammar(grammarN5Raw, CLEAN_SLICE_LEVEL);
}
